#!/bin/bash

export DISPLAY=:0
export XAUTHORITY=/home/christian/.Xauthority

while true; do

   IMAGE=$(find ~/Dropbox/wallpapers -type f \( -name '*.jpg' -o -name '*.png' \) -print0 | shuf -n1 -z)
   gsettings set org.gnome.desktop.background picture-uri "file://$IMAGE"
   sleep 30m

done
