#!/bin/bash

echo '{"version":1}'

# Begin the endless array.
echo '['

# We send an empty first array of blocks to make the loop simpler:
echo '[],'

conky -i 1 -c /home/christian/.conkyrc 2>~/.conkylog

# Now send blocks with information forever:
exec conky -p 2 -c /home/christian/.conkyrc-i3

