#!/bin/bash

if [ -f $HOME/.config/dmenurc ]; then
   . $HOME/.config/dmenurc
else
   DMENU="dmenu -i"
fi

DMENU="$DMENU -p 'MPD Contrl: '"
options="toggle\nnext\nprev\nclear\nrandom\nupdate\nstop\nall\nHeadphones\nSpeakers\nPlaylist"
CMD=$(printf "$options" | eval $DMENU)


if [ $? -eq 0 ]; then
   if [[ "$CMD" == "all" ]]; then
      mpc clear
      mpc listall | mpc add
      mpc random on
      mpc play
   elif [[ "$CMD" == "Headphones" ]]; then
      mpc enable 3
      mpc disable 2
   elif [[ "$CMD" == "Speakers" ]]; then
      mpc enable 2
      mpc disable 3
   else
      mpc $CMD
   fi
fi
