#!/bin/bash

#script to mount an ftp folder, must be run as root


#if [[ $EUID != 0 ]]; then
#   echo "Must be run as root"
#   exit 1
#fi

modprobe fuse

#make sure a username and host is passed
if [[ $# -ne 3 ]]; then
   echo "Usage: ftpfs [user] [host_ip] [host name]"
   exit 1
fi

USER=$1

HOST_IP=$2

HOSTNAME=$3

if [ ! -d "/home/christian/ftp/$USER@$HOSTNAME" ]; then
   mkdir "/home/christian/ftp/$USER@$HOSTNAME"
   #chown christian:users "/home/christian/ftp/$USER@$HOSTNAME"
fi

echo -n "FTP Server password:"

read -s PASSWORD

curlftpfs $HOST_IP "/home/christian/ftp/$USER@$HOSTNAME" -o user=$USER:$PASSWORD




