#!/bin/bash

#script to mount an Network folder, must be run as root


#if [[ $EUID != 0 ]]; then
#   echo "Must be run as root"
#   exit 1
#fi

modprobe fuse

#make sure a username and host is passed
if [[ $# -ne 5 ]]; then
   echo "Usage: ftpfs [user] [host_ip] [host name] [port] [host directory]"
   exit 1
fi

USER=$1

HOST_IP=$2

HOSTNAME=$3

PORT=$4

HOST_DIR=$5
if [ ! -d "/home/christian/Network/$USER@$HOSTNAME" ]; then
   mkdir "/home/christian/Network/$USER@$HOSTNAME"
fi

sshfs $USER@$HOSTNAME:$HOST_DIR /home/christian/Network/$USER@$HOSTNAME -p $PORT
