#!/bin/bash

DMENU="dmenu -p 'Kill Process: ' -dim .5 -w 1000 -l 768 -y 0 -x 0 -i -fn 'Terminus-10:normal'"


PROCESS=$(ps -U christian -u christian u --no-headers --sort pcpu | eval $DMENU)

if [ $? -eq 0 ]; then
   PID=$(echo "$PROCESS" | awk '{print $2}')
   kill $PID
fi
