#!/bin/bash

battery='-';
bat_dir="/sys/class/power_supply/BAT1";

if [ -d "$bat_dir" ]; then
   remaining="$(cat $bat_dir/charge_now)"
   state="$(cat $bat_dir/status)"
   total="$(cat $bat_dir/charge_full)"
   battery_level="$((remaining *100 /total))"
   battery="${battery_level}"
fi 

if [ "$state" == "Discharging" ] && (( "${battery}" <= 3 )); then
   systemctl suspend
fi
