#!/bin/bash

SERVERIP=192.168.0.14
IS_UP=true
DEFAULT_GW=192.168.0.1

while true; do

   #don't bother pinging if outside the network
   if [[ "$(ip route show | grep default | awk '{print $3}')" == "$DEFAULT_GW" ]]; then

      #ping the server, and send an email if its down unless we already know it's down
      ping -q -c 1 -W 1 $SERVERIP > /dev/null

      if [ $? -ne 0 ]; then

         $IS_UP && echo "Pi is down" | mail -s "Pi is down" christianbboman@gmail.com

         IS_UP=false
      else

         IS_UP=true
      fi
   
      sleep 15m
   fi
done
