#!/bin/bash


CMDS="next
prev
toggle
clear"


HOSTS="0
rpi"

if [ -f $HOME/.dmenurc ];then
	source $HOME/.dmenurc
	DMENU="$DMENU -p 'MPD Control'"
else
	DMENU="dmenu -i -p 'MPD Control'"
fi

HOST=$(echo "$HOSTS" | eval $DMENU)

if [ $? -eq 0 ];then
	CMD=$(echo "$CMDS" | eval $DMENU)
	if [ $? -eq 0 ]; then
		mpc -h $HOST $CMD
	fi
fi
