#!/bin/bash

if [ -f $HOME/.dmenurc ];then
   source $HOME/.dmenurc
   DMENU="$DMENU -p 'MPD Quick Play'"
else
   DMENU="dmenu -i -p 'MPD Quick Play'"
fi

mpc -q clear;

RESULTS=$(mpc listall | eval $DMENU)

if [ $? -eq 0 ]; then
   mpc -q add "$RESULTS";
   mpc -q play
fi

exit
