#!/bin/bash

mpc -q clear

if [ -f $HOME/.dmenurc ]; then
   source $HOME/.dmenurc
   DMENU="$DMENU -p 'MPD add'"
else
   DMENU="dmenu -i"
fi

QUERY_TYPES="artist
album
title"

QUERY_TYPE=$(echo "$QUERY_TYPES" | eval $DMENU)

if [ $? -eq 0 ]; then
   RESULTS=$( mpc -q list "$QUERY_TYPE" | eval $DMENU )
   if [ $? -eq 0 ]; then
      mpc -q findadd "$QUERY_TYPE" "$RESULTS"
      mpc -q play
   fi
fi
