#!/bin/bash

if [ -f $HOME/.config/dmenurc ];then
   source $HOME/.config/dmenurc
   DMENU="$DMENU -p 'Session Menu'"
else
   DMENU="dmenu -i -p 'Session Menu'"
fi

CMD=$(printf "Lock Screen\nLogout ${USER^}\nsuspend\nreboot\npoweroff" | eval $DMENU)


if [ $? -eq 0 ]; then
   case "$CMD" in
      "Lock Screen")
         xautolock -locknow
      ;;
      "Logout ${USER^}")
         i3 exit
      ;;
      "Headphones")
         mpc enable 3
         mpc disable 2
      ;;
      "Speakers")
         mpc enable 2
         mpc disable 3
      ;;
      *)
      systemctl $CMD
      ;;
   esac

fi
