#!/bin/bash

if [ -f $HOME/.dmenurc ];then
   source $HOME/.dmenurc
   DMENU="$DMENU -p 'Session Menu'"
else
   DMENU="dmenu -i -p 'Session Menu'"
fi

CMD=$(printf "Lock Screen\nLogout ${USER^}\nSuspend\nRestart\nShut Down" | eval $DMENU)


   case "$CMD" in
      "Lock Screen")
         i3lock -u -i ~/pictures/wallpapers/aperture_science.png
      ;;
      "Logout")
         i3 exit
      ;;
      "Suspend")
         sudo systemctl suspend
      ;;
      "Restart")
         sudo systemctl reboot
      ;;
      "Shut Down")
         sudo systemctl poweroff
      ;;
   esac
