#!/bin/bash


#get on to the VPN
if [ ! -f /var/run/vpnc/pid ]; then
   echo "Please enter your password for UCD VPN:"

   read -s PASSWORD

   printf "$PASSWORD\n" | sudo -S vpnc
fi

sshfs bomanc@csegrid.ucdenver.pvt:/export/homes/bomanc ~/ftp/ucd -C -p 22


