#!/bin/bash

AUR_DIR=/home/christian/.aur
MAKEPKG="makepkg -fc"
PASSWORD=$(~/.bin/dpass)

for i in $AUR_DIR/*-git; do

   cd $i
   eval $MAKEPKG

   echo $PASSWROD | sudo -s pacman -U --noconfirm $i.pkg.tar.gz 

   cd $AUR_DIR

done
